import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<header className="shadow-md">
					<div className="w-[90%] mx-auto py-2">
						<h1 className="text-blue-600 font-extrabold text-5xl">MMWS.</h1>
					</div>
				</header>
				<main className="w-[90%] mx-auto my-4">
					{children}
				</main>
			</body>
		</html>
	);
}
